Traceback (most recent call last):
  File "errorExample.py", line 23, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
